### ISSUE TITLE
show Lead ID as a field

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/docs.leadconduit.com#16]
Requested by [support](https://github.com/activeprospect/leadconduit-fields/issues/37). Also include other automatic/system values, like "Source", possibly.

**Comment by alexkwolfe** [comment]
I propose a new page on the docs site that lists lead metadata. Lead ID and Source aren't fields in that you can't populate them with data, like you can all the other fields currently shown. There are no associate parameters, etc.

**Comment by kcaponeAP** [comment]
This came up again today, as we were discussing Lead ID versus LeadiD ID. 
It wasn't initially clear what purpose Lead ID served versus LeadiD ID, especially since Lead ID was missing from the docs page.

**Comment by alexkwolfe** [comment]
Lead ID isn't a field. A field is something that can be provided by a lead vendor. Lead ID is an internal data point that we generate. That's why it's not shown not the fields documentation page.

LeadiD ID is a field. It is provided by the vendor. That's why it's shown in the fields documentation page. 

If we're going to document our internal lead metadata  (such a Lead ID and Lead Timestamp), they should go on a completely different documentation page.

**Comment by kcaponeAP** [comment]
Yes, we need lead metadata documented in the same manner as fields. Probably not on the same page, as you say, but in a separate / third category on docs.leadconduit.com perhaps.
