### ISSUE TITLE
Please allow is_military to be searched easier on docs.leadconduit.com

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/docs.leadconduit.com#17]
Often I need to locate the 'military' status field. It is not locatable if I search military. I have to preface my search with is.. in order to locate this field. Please allow this to be located by searching 'military'

**Comment by cgrayson** [comment]
Searching for "military" _does_ show the `is_military`/"Application Is Military" field in the results. I think the problem is that it's also showing a lot of other fields, as well. That's because those are all part of the Military.com inbound integration, which also happens to match the search for just "military".

Not sure how to fix that without adding to the complexity of the search ("only match on field names" vs "match on anything" etc.)… Could possibly have this search on the `/fields` page _not_ include matches on integration name, I suppose. It's already possible to see all of Military.com's fields on the `/integrations` page, so maybe that doesn't lose much?

**Comment by kcaponeAP** [comment]
i agree that it's returning a lot more than i bargained for and i have to scroll to actually find the field i want.

it does seem that the search behaviour has changed since i opened the issue. im not sure what is the acceptable response to a search though. however, when i want to locate a field for military, i'm not exactly getting the results i expect.

**Comment by cgrayson** [comment]
Would you rather it stopped showing matches based on integration name? If it didn't show Military.com matches, then searching for "military" would show the field with that name more clearly. 

But the tradeoff is that if anyone _wants_ to search fields by integration name, say, ["tree", for example](http://docs.leadconduit.com/fields?q=tree), then it wouldn't show any of the standard fields that don't have "tree" in their name (like "First Name", "Last Name", etc.). But the list of LendingTree's fields is available on the [integrations page](http://docs.leadconduit.com/integrations?q=tree), so maybe that's ok.

**Comment by alexkwolfe** [comment]
I'm pretty sure the integrations page links back to the fields page in order to show all fields for that integration. The reason it does this is that the integrations page doesn't show complete information about each field.

**Comment by cgrayson** [comment]
Ah, right. [Like this](http://docs.leadconduit.com/fields?q=lendingtree%20inbound%20multiformat). So it's relying on matching on integration name for that.
